# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package*.json tsconfig.json ./
COPY mcp-server.ts .
RUN npm install --ignore-scripts && npm run build

FROM node:lts-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

USER node

ENTRYPOINT ["node", "dist/mcp-server.js"]
